name: PR Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Get Environment Variables
        id: get-env-vars
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
            PR_PREVIEW_*, ${{ github.event.repository.name }}/pr-${{ github.event.pull_request.number }}
          parse-json-secrets: true
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Create Environment File
        run: |
          echo "REACT_APP_PR_NUMBER=${{ github.event.pull_request.number }}" >> .env
          echo "REACT_APP_BRANCH_NAME=${{ github.head_ref }}" >> .env
          for secret in $(echo '${{ toJSON(steps.get-env-vars.outputs) }}' | jq -r 'to_entries | .[] | .key + "=" + .value'); do
            echo "REACT_APP_$secret" >> .env
          done

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          CI: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync build/ s3://${{ secrets.AWS_S3_BUCKET_NAME }}/pr-${{ github.event.pull_request.number }} --delete

      - name: Create CloudFront Invalidation
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/pr-${{ github.event.pull_request.number }}/*"

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          script: |
            const previewUrl = `https://${{ secrets.CLOUDFRONT_DISTRIBUTION_DOMAIN_NAME }}/pr-${{ github.event.pull_request.number }}/`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Preview deployment is ready!\n\n- Preview URL: ${previewUrl}\n- Branch: \`${{ github.head_ref }}\`\n- Commit: \`${{ github.sha }}\``
            }); 